name: Solr Almaren
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-20.04
    env:
      AZURE_TOKEN: ${{secrets.AZURE_TOKEN}}
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Solr Connector
        run: |
          curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=7.7.2 bash
          rm ./solr-7.7.2/server/solr/configsets/_default/conf/managed-schema
          cp src/test/resources/data/managed-schema ./solr-7.7.2/server/solr/configsets/_default/conf
          ./solr-7.7.2/bin/solr delete -c gettingstarted
          ./solr-7.7.2/bin/solr create -c gettingstarted
      - name: Connect to PostgreSQL
        run: |
          set -e
          PGPASSWORD="postgres" psql -h localhost -U postgres -c "ALTER USER postgres PASSWORD 'postgres' ;"
          PGPASSWORD="postgres" psql -h localhost -U postgres -c "create database almaren;"
          PGPASSWORD="postgres" psql -c 'create role runner;' -U postgres -h localhost
          PGPASSWORD="postgres" psql -c 'ALTER ROLE "runner" WITH  LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;' -U postgres -h localhost
      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Build and test scala
        run: |
          sbt ++2.12.15 test
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true